name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

permissions:
  # Allows junit report to be written. See action-junit-report's README.
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pacman-catalog
        uses: actions/checkout@v7

      - name: Install Open Dylan
        uses: dylan-lang/install-opendylan@v3

      # Update the local workspace using the local checkout as the catalog so that
      # updates to Deft itself will be installed if we're testing a new version of Deft.
      - name: Update workspace
        run: DYLAN_CATALOG=. deft update

      # Build the test suite using the dylan-tool sources specified in
      # dev-dependencies so we get the latest.
      - name: Run tests
        run: DYLAN_CATALOG=. deft test -- --report surefire --report-file _build/test-output.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          annotate_only: true
          report_paths: '**/_build/test-output.xml'
          detailed_summary: true
          include_passed: true
