name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pacman-catalog
        uses: actions/checkout@v4

      - name: Install Open Dylan
        uses: dylan-lang/install-opendylan@v3.0.1

      # Use dylan-tool from the Open Dylan install to update the local
      # workspace.  Use the local checkout as the catalog so that updates to
      # dylan-tool itself will be installed if we're testing a new version of
      # dylan-tool.
      - name: Update Dylan workspace
        run: |
          DYLAN_CATALOG=. dylan update

      # Build the test suite using the dylan-tool sources specified in
      # dev-dependencies so we get the latest.
      - name: Build pacman-catalog-test-suite
        run: |
          dylan build pacman-catalog-test-suite

      # Run the test suite against the checked out catalog.
      - name: Run pacman-catalog-test-suite
        run: |
          DYLAN_CATALOG=. _build/bin/pacman-catalog-test-suite --report surefire --report-file _build/pacman-catalog-tests.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/_build/*-tests.xml'
          detailed_summary: true
          include_passed: true
